import "@/app/globals.css";
import type { Metadata } from "next";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { Role } from "@prisma/client";

export const metadata: Metadata = {
  title: {
    template: "%s - Administracion",
    default: "Administracion",
  },
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session?.user) redirect("/auth/login");
  if (session.user.role !== Role.ADMIN) return <div>No tienes permisos</div>;
  return <>{children}</>;
}
