import "@/app/globals.css";
import { Header } from "@/components/navigation/header";
import { Sidebar } from "@/components/navigation/sidebar";
import { bodyFont } from "@/components/typography/fonts";
import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s - Teslo Shop",
    default: "Teslo Shop",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body className={`${bodyFont} antialiased max-w-7xl md:mx-auto`}>
        <SessionProvider>
          <Header />
          <Sidebar />
          <main className="flex flex-col gap-8 py-4 md:py-10 px-4 md:px-0">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
